---
- name: Add rpm fusion non-free repository
  become: yes
  shell: dnf install --nogpgcheck http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-24.noarch.rpm

- name: Add rpm fusion free repository
  become: yes
  shell: dnf install --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-24.noarch.rpm
  
- name: Install Packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - a

