# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PATH=~/.npm-global/bin:$PATH
export FORGE_HOME=~/Tools/forge/forge-distribution-1.4.0.Final
export PATH=$PATH:$FORGE_HOME/bin
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias ll='ls -alhr --color=auto'
alias powersave='sudo tuned-adm profile powersave'
alias balanced='sudo tuned-adm profile balanced'
alias performance='sudo tuned-adm profile throughput-performance'
alias update='sudo yum update -y'
alias pajammery="ssh root@45.55.66.249"
